Calendar Element
python-gsoc/python-blogs pull request #47
Opened 2019-03-02 23:06 UTC by MastersAbh

Calendar template added which detects the Timezone of the user and displays the calendar accordingly. 
I have added a link on the homepage as a rough work. Please give your comments on this.

2019-03-03 00:01 UTC, botanicvelious commented
1) please fix the mainpage template so it isnt a pure link, you can see how it should work at http://python-gsoc.org/deadlines.html
2) please dont commit the project.db
3) from django.urls import path is in urls.py twice

2019-03-03 00:51 UTC, MastersAbh commented
#38 Calendar page element -- Made the changes required.

2019-03-03 01:39 UTC, botanicvelious commented
your commit actually deletes the project.db now

Also on the homepage it still says "<a href="\calendar">GO TO CALENDAR</a>"

Lastly, it looks like /en/schedule/ was not updated to use your template but you are directing to /calendar/. 

Other then that looks good.

2019-03-03 01:42 UTC, botanicvelious commented
Looks like you also left

<p>Interested in volunteering with the Python Software Foundation?  {{ TIME_ZONE }}</p>

in the mentors template.

2019-03-03 11:38 UTC, MastersAbh commented
Hey, had some questions.

2019-03-03 15:25 UTC, Gouravchawla commented
> Hey, had some questions.

Just ask the question. People here reside in different timezones and they might not be active at the given moment. So, just ask the question and whenever someone is online, they would answer your question.

2019-03-03 18:14 UTC, botanicvelious commented
@MastersAbh what questions?

2019-03-03 18:18 UTC, MastersAbh commented
Hey, No questions. Was stuck at a point, that I was able to figure out. 
Anyway, please review the changes. :)

2019-03-03 18:33 UTC, botanicvelious requested changes
- [ ] I see no changes to the schedule template
>python-blogs/gsoc/templates/schedule.html
- [ ] the project.db is still being erased by this pr

- [ ] other review items below as well



>

2019-03-03 18:33 UTC, botanicvelious commented on gsoc/templates/homepage.html
> +	<a href="\calendar">GO TO CALENDAR</a>
Why is this still here?

2019-03-03 18:33 UTC, botanicvelious commented on gsoc/templates/mentors.html
> +			<p>Interested in volunteering with the Python Software Foundation?  {{ TIME_ZONE }}</p>
Left over Debug data?

2019-03-03 18:33 UTC, botanicvelious commented on gsoc/urls.py
> +urlpatterns += [path('calendar/', views.calender)]
this still needed?

2019-03-03 18:33 UTC, botanicvelious commented on gsoc/urls.py
> +from . import views
unneeded now?

2019-03-03 18:33 UTC, botanicvelious commented on gsoc/views.py
> +from django.http import HttpResponse
Is any of this needed if you are using a tag?

2019-03-03 18:45 UTC, MastersAbh commented
I am just not committing project.db . Is it still deleting it for you?

2019-03-03 19:32 UTC, botanicvelious commented
> 
> 
> I am just not committing project.db . Is it still deleting it for you?

https://github.com/python-gsoc/python-blogs/pull/47/files

You can see at the bottom BIN -1.24 MB project.db

2019-03-03 20:24 UTC, botanicvelious commented
Looks good just fix the project.db issue and its good to go.

2019-03-03 20:25 UTC, botanicvelious approved these changes

2019-03-03 20:34 UTC, botanicvelious requested changes
Don't delete project.db

2019-03-04 06:10 UTC, botanicvelious approved these changes

2019-03-04 06:10 UTC, merged